version: "3.5"

services:
  obd:
    build: obd
    restart: unless-stopped
    tty: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

  camera:
    build: camera
    restart: unless-stopped
    tty: true
    volumes:
      - "./camera/out:/usr/src/app/out"
    devices:
      - "/dev/video0:/dev/video0"
